### ISSUE TITLE
NodeJS: WebSocket is not defined

### ISSUE THREAD

**Issue by jimmylee** [textileio/js-hub#352]
# Is this a bug?

When calling `await buckets.list()` I receive the following error on a nodeJS server:

```sh
ReferenceError: WebSocket is not defined
    at Object.start (/Users/riverlands/Development/slate/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:23024)
    at e.start (/Users/riverlands/Development/slate/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:6314)
    at Object.t.unary (/Users/riverlands/Development/slate/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:24995)
    at Promise (/Users/riverlands/Development/slate/node_modules/@textile/buckets/src/api/index.ts:79:12)
    at new Promise (<anonymous>)
    at Buckets.unary (/Users/riverlands/Development/slate/node_modules/@textile/buckets/src/api/index.ts:77:12)
    at Object.<anonymous> (/Users/riverlands/Development/slate/node_modules/@textile/buckets/src/api/index.ts:194:36)
    at Generator.next (<anonymous>)
    at /Users/riverlands/Development/slate/node_modules/@textile/buckets/dist/api/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/riverlands/Development/slate/node_modules/@textile/buckets/dist/api/index.js:4:12)
    at Object.bucketsList (/Users/riverlands/Development/slate/node_modules/@textile/buckets/dist/api/index.js:157:12)
    at Buckets.<anonymous> (/Users/riverlands/Development/slate/node_modules/@textile/buckets/src/buckets.ts:245:12)
    at Generator.next (<anonymous>)
    at /Users/riverlands/Development/slate/node_modules/@textile/buckets/dist/buckets.js:8:71
    at new Promise (<anonymous>)
```

* I'm expecting to be able to use `import { Buckets, UserAuth } from "@textile/hub";` on the server.
* I don't need `WebSocket`, maybe that code can be wrapped in an if statement for `process.browser` or something.

### Details

**Node Version**: `v10.11.0`
**Where do you try to do this?**: https://github.com/filecoin-project/slate/blob/main/pages/api/hydrate.js#L32

**Comment by andrewxhill** [comment]
Could you run an update on `@textile/hub`, 0.4.0 should be the ticket, i believe no further `ws` install requirement on node apps.
